### ISSUE TITLE
When the code is available?

### ISSUE THREAD

**Issue by Kazimbalti** [uzh-rpg/agilicious#11]
Hello sir

Thank you for open-sourcing the code for this paper.
Please can you tell me when you will release the code?
Thank you

**Comment by roangel** [comment]
Hello, the code is open for requests here: https://agilicious.readthedocs.io/en/latest/index.html

**Comment by dh12121** [comment]
Excuse me, I would like to ask, have you obtained the source code access license? How long did it take from application to reply?

**Comment by Kazimbalti** [comment]
Sorry for late response,
Still I haven't received the code.

Please give me access to the code.
thank you
