### ISSUE TITLE
Drone building, BOM and 3D print files

### ISSUE THREAD

**Issue by MichaelBosello** [uzh-rpg/agilicious#2]
Dears,

Do you plan to provide a BOM more detailed than the table presented in the paper? Will you open source also the files to 3D print the custom parts?

Thank you.

**Comment by kelia** [comment]
We prepared a detailed parts list to reproduce the hardware platform, including the files to 3D print custom parts. 
We are releasing the hardware list and software very soon!

**Comment by MichaelBosello** [comment]
Ok thank you. Looking forward to the release.
