### ISSUE TITLE
Teaching video

### ISSUE THREAD

**Issue by dh12121** [uzh-rpg/agilicious#39]

**Comment by BladeMonster** [comment]
Excuse me, I would like to ask, have you obtained the source code access license? How long did it take from application to reply?

**Comment by LeshphonCry** [comment]
I applied, but they haven't replied to me 😅. Like you, I am trying to email others to ask, but no results yet. My friend, if either of us gets the source code we can share it with each other.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/14/2023 17:24 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [uzh-rpg/agilicious] Teaching video (Issue #39) |

Excuse me, I would like to ask, have you obtained the source code access license? How long did it take from application to reply?

**Comment by BladeMonster** [comment]
Hello, I would like to inquire if you have already obtained the access permission to the source code. If so, how long did it take from submitting the application to getting the access permission?

**Comment by LeshphonCry** [comment]
> 

兄弟，我也是北航的，应该怎么联系你？

**Comment by BladeMonster** [comment]
wx:buaa_hf
