### ISSUE TITLE
doxygen not working

### ISSUE THREAD

**Issue by mb9041** [uzh-rpg/agilicious#46]
I am unable to open the agilicious documentation through doxygen.  I get numerous errors when following these directions:

```
Install doxygen sudo apt install doxygen
Run doxygen in the root folder agilicious/ by simply issuing the doxygen command.
Open the documentation in your favourite browser by clicking agilicious/docs/html/index.html!
```

Has anyone else had this issue? Please advise.

**Comment by dagouxiong233** [comment]
Did you get it back? I've been doing some research on this subject, so can you please give me a code ? I'm very impressed, 605572368@qq.com,As soon as I can solve your problem, I will notify you at the first hour.
